language: cpp
sudo: required
services:
    - docker
dist: trusty
os: linux
env:
    - JOB=build
    - JOB=test
    - JOB=lint
cache:
  directories:
  - $HOME/.cache/bazel
install: skip
before_script:
    - cp scripts/AGREEMENT.txt ${HOME}/.apollo_agreement.txt
script:
    - ./docker/scripts/dev_start.sh
    - ./apollo_docker.sh ${JOB}
    - rm -rf "${HOME}/.cache/bazel/_bazel_${USER}/install"
notifications:
    email:
        on_success: change
        on_failure: always
