# safelist
branches:
  only:
  - master

language: cpp
sudo: required
services:
    - docker
dist: trusty
os: linux
cache:
  directories:
  - $HOME/.cache/bazel
install: skip
before_script:
    - cp scripts/AGREEMENT.txt ${HOME}/.apollo_agreement.txt

jobs:
  include:
    - stage: stage-01
      env:
        - JOB=lint
      script:
        - |  # Lint only when C/C++ files changed.
          git diff --name-only HEAD...$TRAVIS_BRANCH
          exit 0

          git diff --name-only HEAD...$TRAVIS_BRANCH | \
              grep -e '.cc$' -e '.h$' -e '/BUILD$'
          if [ $? -ne 0 ]; then
            exit 0
          fi
        - ./docker/scripts/dev_start.sh -t dev-x86_64-20190413_1615 --fast-build
        - ./apollo_docker.sh ${JOB}
        - rm -rf "${HOME}/.cache/bazel/_bazel_${USER}/install"
        - rm -rf "/apollo/data/core"
    - stage: stage-02
      if: branch = master
      env:
        - JOB=cibuild
      script:
        - |  # Build only when C/C++ files changed.
          git diff --name-only HEAD...$TRAVIS_BRANCH | \
              grep -e '.c$' -e '.cc$' -e '.cpp$' -e '.h$' -e '/BUILD$'
          if [ $? -ne 0 ]; then
            exit 0
          fi
        - ./docker/scripts/dev_start.sh -t dev-x86_64-20190413_1615 --fast-build
        - ./apollo_docker.sh ${JOB}
        - rm -rf "${HOME}/.cache/bazel/_bazel_${USER}/install"
        - rm -rf "/apollo/data/core"
    - # stage: stage-02
      env:
        - JOB=cibuild_extended
      script:
        - |  # Build only when C/C++ files changed.
          git diff --name-only HEAD...$TRAVIS_BRANCH | \
              grep -e '.c$' -e '.cc$' -e '.cpp$' -e '.h$' -e '/BUILD$'
          if [ $? -ne 0 ]; then
            exit 0
          fi
        - ./docker/scripts/dev_start.sh -t dev-x86_64-20190413_1615 --fast-build
        - ./apollo_docker.sh ${JOB}
        - rm -rf "${HOME}/.cache/bazel/_bazel_${USER}/install"
        - rm -rf "/apollo/data/core"
    - # stage: stage-02
      env:
        - JOB=citest_basic
      script:
        - |  # Ignore test-irrelevant files.
          git diff --name-only HEAD...$TRAVIS_BRANCH | \
              grep -v '.md$' | \
              grep -v '.py$'
          if [ $? -ne 0 ]; then
            exit 0
          fi
        - ./docker/scripts/dev_start.sh -t dev-x86_64-20190413_1615 --fast-test
        - ./apollo_docker.sh ${JOB}
        - rm -rf "${HOME}/.cache/bazel/_bazel_${USER}/install"
        - rm -rf "/apollo/data/core"
    - # stage: stage-02
      env:
        - JOB=citest_extended
      script:
        - |  # Ignore test-irrelevant files.
          git diff --name-only HEAD...$TRAVIS_BRANCH | \
              grep -v '.md$' | \
              grep -v '.py$'
          if [ $? -ne 0 ]; then
            exit 0
          fi
        - ./docker/scripts/dev_start.sh -t dev-x86_64-20190413_1615 --fast-test
        - ./apollo_docker.sh ${JOB}
        - rm -rf "${HOME}/.cache/bazel/_bazel_${USER}/install"
        - rm -rf "/apollo/data/core"
notifications:
    email:
        on_success: always
        on_failure: always
